import { BrowserWindow, session, app } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { spawn } from 'child_process';
import { getYtDlpPath } from './ytDlpService';

/* ── Constants ────────────────────────────────────────────── */

/** Dedicated session partition — 'persist:' prefix makes Electron persist
 *  this session to disk automatically across app restarts. */
const SESSION_PARTITION = 'persist:facebook';

/** Path where the exported Netscape cookie file is written for yt-dlp. */
const COOKIES_FILE_PATH = path.join(app.getPath('userData'), 'facebook_cookies.txt');

/** The two cookies whose presence confirms an active Facebook session. */
const AUTH_COOKIES = ['c_user', 'xs'];

/* ── FacebookSessionManager ───────────────────────────────── */

class FacebookSessionManager {

  /** Cached --cookies-from-browser args from the last successful tryChromeBridge() probe.
   *  Reset when the session is cleared so the next call re-probes. */
  private _workingBrowserArgs: string[] = [];

  /* ── METHOD 1: isLoggedIn ─────────────────────────────── */

  /** Returns true only when BOTH auth cookies ('c_user' and 'xs')
   *  are present in the dedicated Facebook session. */
  async isLoggedIn(): Promise<boolean> {
    try {
      const sess = session.fromPartition(SESSION_PARTITION);
      const cookies = await sess.cookies.get({ domain: 'facebook.com' });
      const names = new Set(cookies.map(c => c.name));
      return AUTH_COOKIES.every(name => names.has(name));
    } catch (err: any) {
      console.error('[FacebookSession] isLoggedIn error:', err.message);
      return false;
    }
  }

  /* ── METHOD 2: openLoginWindow ────────────────────────── */

  /** Opens a dedicated BrowserWindow that loads the Facebook login page
   *  inside the isolated session partition.
   *  Polls every 2 s for successful login; times out after 10 minutes.
   *  Returns true if the user logged in, false if cancelled / timed out. */
  async openLoginWindow(): Promise<boolean> {
    return new Promise<boolean>((resolve) => {
      let resolved = false;

      const win = new BrowserWindow({
        width: 900,
        height: 700,
        title: 'Connect Facebook Account',
        autoHideMenuBar: true,
        webPreferences: {
          session: session.fromPartition(SESSION_PARTITION),
          nodeIntegration: false,
          contextIsolation: true,
        },
      });

      win.loadURL('https://www.facebook.com/login');

      /* Polling: check for successful login every 2 seconds */
      const pollInterval = setInterval(async () => {
        try {
          const loggedIn = await this.isLoggedIn();
          if (loggedIn) {
            clearInterval(pollInterval);
            clearTimeout(timeoutHandle);
            resolved = true;

            // Give Facebook's login redirect 1 second to settle and flush
            // all session cookies before we export them.
            await new Promise(r => setTimeout(r, 1000));

            // Export cookies for yt-dlp before closing
            try {
              await this.exportCookiesFile();
            } catch (exportErr: any) {
              console.error('[FacebookSession] Cookie export error:', exportErr.message);
            }

            win.close();
            resolve(true);
          }
        } catch {
          // Ignore transient errors during polling
        }
      }, 2000);

      /* Timeout: give up after 10 minutes */
      const timeoutHandle = setTimeout(() => {
        clearInterval(pollInterval);
        if (!win.isDestroyed()) {
          win.close();
        }
        if (!resolved) {
          resolved = true;
          resolve(false);
        }
      }, 10 * 60 * 1000);

      /* Handle user manually closing the window */
      win.on('closed', () => {
        clearInterval(pollInterval);
        clearTimeout(timeoutHandle);
        if (!resolved) {
          resolved = true;
          resolve(false);
        }
      });
    });
  }

  /* ── METHOD 3: exportCookiesFile ─────────────────────── */

  /** Exports all facebook.com cookies from the dedicated session to a
   *  Netscape/Mozilla cookie file that yt-dlp can consume via --cookies. */
  async exportCookiesFile(): Promise<string> {
    const sess = session.fromPartition(SESSION_PARTITION);
    const allCookies = await sess.cookies.get({});
    const fbCookies = allCookies.filter(c => c.domain && c.domain.includes('facebook.com'));

    if (fbCookies.length === 0) {
      throw new Error('No Facebook session found. Please login first.');
    }

    const lines: string[] = [
      '# Netscape HTTP Cookie File',
      '# Generated by VideoDownloader',
      '',
    ];

    for (const cookie of fbCookies) {
      // Ensure domain always starts with '.' (Netscape format)
      const domain = cookie.domain?.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
      const flag   = 'TRUE';
      const cookiePath = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expiry = Math.floor(cookie.expirationDate ?? 0);
      const name   = cookie.name;
      const value  = cookie.value;

      lines.push([domain, flag, cookiePath, secure, expiry, name, value].join('\t'));
    }

    fs.writeFileSync(COOKIES_FILE_PATH, lines.join('\n') + '\n', 'utf-8');

    // Restrict file permissions on non-Windows platforms
    if (process.platform !== 'win32') {
      fs.chmodSync(COOKIES_FILE_PATH, 0o600);
    }

    console.log(`[FacebookSession] Cookies exported to: ${COOKIES_FILE_PATH} (${fbCookies.length} cookie(s))`);
    return COOKIES_FILE_PATH;
  }

  /* ── METHOD 4: clearSession ───────────────────────────── */

  /** Clears all stored data from the dedicated Facebook session partition
   *  and deletes the exported cookies file if it exists. */
  async clearSession(): Promise<void> {
    await session.fromPartition(SESSION_PARTITION).clearStorageData();

    if (fs.existsSync(COOKIES_FILE_PATH)) {
      fs.unlinkSync(COOKIES_FILE_PATH);
    }

    // Reset cached browser probe result so the next getWorkingCookieArgs() re-probes
    this._workingBrowserArgs = [];

    console.log('[FacebookSession] Session cleared');
  }

  /* ── METHOD 5: getStoredCookiesPath ───────────────────── */

  /** Returns the expected path of the exported cookies file.
   *  Does NOT check whether the file actually exists. */
  getStoredCookiesPath(): string {
    return COOKIES_FILE_PATH;
  }

  /* ── METHOD 6: isCookiesFileStale ─────────────────────── */

  /** Returns true if the cookies file is missing or was last modified
   *  more than 60 minutes ago, signalling that a fresh export is needed. */
  isCookiesFileStale(): boolean {
    if (!fs.existsSync(COOKIES_FILE_PATH)) {
      return true;
    }

    const { mtimeMs } = fs.statSync(COOKIES_FILE_PATH);
    const ageMs = Date.now() - mtimeMs;
    const SIXTY_MINUTES_MS = 60 * 60 * 1000;
    return ageMs > SIXTY_MINUTES_MS;
  }

  /* ── METHOD 7: tryChromeBridge ───────────────────────── */

  /** Probes installed system browsers in order, using yt-dlp's
   *  --cookies-from-browser flag against a public Facebook page.
   *  Returns a status code; never throws.
   *
   *  Return values:
   *    'success'      — a browser yielded working cookies; _workingBrowserArgs is set
   *    'locked'       — a browser was found but its DB is locked (user has it open)
   *    'not-logged-in'— browsers were found but none had an active FB session
   *    'not-found'    — yt-dlp binary missing or OS-level spawn error
   */
  async tryChromeBridge(): Promise<'success' | 'locked' | 'not-logged-in' | 'not-found'> {
    const BROWSER_CANDIDATES = [
      'chrome',
      'chrome:profile=Profile 1',
      'edge',
      'firefox',
    ];

    let ytDlpPath: string;
    try {
      ytDlpPath = getYtDlpPath();
      if (!fs.existsSync(ytDlpPath)) {
        console.warn('[FacebookSession] yt-dlp binary not found at:', ytDlpPath);
        return 'not-found';
      }
    } catch (err: any) {
      console.error('[FacebookSession] Could not resolve yt-dlp path:', err.message);
      return 'not-found';
    }

    for (const candidate of BROWSER_CANDIDATES) {
      console.log('[FacebookSession] Trying browser:', candidate);

      const result = await new Promise<{ code: number | null; stderr: string }>((resolve) => {
        let stderr = '';
        let settled = false;

        let proc: ReturnType<typeof spawn>;
        try {
          proc = spawn(
            ytDlpPath,
            [
              '--cookies-from-browser', candidate,
              '--skip-download',
              '--no-warnings',
              '--print', '%(extractor)s',
              'https://www.facebook.com/',
            ],
            {
              windowsHide: true,
              env: { ...process.env, PYTHONIOENCODING: 'utf-8' },
            },
          );
        } catch (spawnErr: any) {
          console.warn('[FacebookSession] Spawn failed for', candidate, ':', spawnErr.message);
          resolve({ code: -1, stderr: spawnErr.message });
          return;
        }

        const timeout = setTimeout(() => {
          if (!settled) {
            settled = true;
            try { proc.kill(); } catch { /* ignore */ }
            resolve({ code: -1, stderr: 'timeout' });
          }
        }, 8000);

        proc.stderr?.on('data', (data: Buffer) => { stderr += data.toString(); });
        // Drain stdout so the process doesn't stall
        proc.stdout?.on('data', () => { /* noop */ });

        proc.on('close', (code) => {
          if (!settled) {
            settled = true;
            clearTimeout(timeout);
            resolve({ code, stderr });
          }
        });

        proc.on('error', (err: Error) => {
          if (!settled) {
            settled = true;
            clearTimeout(timeout);
            resolve({ code: -1, stderr: err.message });
          }
        });
      });

      const stderrLower = result.stderr.toLowerCase();

      // OS / spawn error — yt-dlp itself could not be launched
      if (result.code === -1 && stderrLower === 'timeout') {
        console.warn('[FacebookSession] Probe timed out for browser:', candidate);
        continue;
      }
      if (result.code === -1) {
        console.warn('[FacebookSession] OS error probing browser:', candidate, result.stderr);
        return 'not-found';
      }

      // Browser DB locked → signal caller immediately so they can show a useful message
      if (stderrLower.includes('database is locked') || stderrLower.includes(' lock')) {
        console.warn('[FacebookSession] Browser DB is locked:', candidate);
        return 'locked';
      }

      if (result.code === 0) {
        // yt-dlp exited cleanly → cookies were accessible
        console.log('[FacebookSession] Browser bridge succeeded with:', candidate);
        this._workingBrowserArgs = ['--cookies-from-browser', candidate];
        return 'success';
      }

      // Non-zero exit — likely not logged in, try next candidate
      if (stderrLower.includes('login') || stderrLower.includes('not logged in')) {
        console.log('[FacebookSession] Not logged in via:', candidate);
      } else {
        console.log('[FacebookSession] Browser probe failed for:', candidate, '(code', result.code + ')');
      }
    }

    return 'not-logged-in';
  }

  /* ── METHOD 8: getWorkingCookieArgs ──────────────────── */

  /** Returns the best available yt-dlp cookie arguments for Facebook.
   *
   *  Priority order:
   *    1. Fresh exported cookies file (< 60 min old)
   *    2. Cached _workingBrowserArgs from a previous successful probe
   *    3. Live tryChromeBridge() probe
   *    4. Re-exported cookies from embedded session (if logged in)
   *    5. [] — no auth (works for public content)
   *
   *  Never throws. Never opens a login window.
   */
  async getWorkingCookieArgs(): Promise<string[]> {
    try {
      // 1. Use our own exported cookies file — refresh it if stale
      if (fs.existsSync(COOKIES_FILE_PATH)) {
        if (!this.isCookiesFileStale()) {
          console.log('[FacebookSession] Using fresh exported cookies file');
          return ['--cookies', this.getStoredCookiesPath()];
        }
        // File exists but is stale — try to refresh it from the embedded session
        console.log('[FacebookSession] Cookies file is stale, attempting refresh...');
        try {
          await this.exportCookiesFile();
          console.log('[FacebookSession] Cookies file refreshed successfully');
          return ['--cookies', this.getStoredCookiesPath()];
        } catch (refreshErr: any) {
          // Embedded session may have expired — fall through to browser bridge
          console.warn('[FacebookSession] Cookie refresh failed, falling through to browser bridge:', refreshErr.message);
        }
      }

      // 2. Re-use a cached successful browser probe without re-running
      if (this._workingBrowserArgs.length > 0) {
        console.log('[FacebookSession] Re-using cached browser args:', this._workingBrowserArgs.join(' '));
        return this._workingBrowserArgs;
      }

      // 3. Probe system browsers
      const bridgeResult = await this.tryChromeBridge();

      if (bridgeResult === 'success') {
        // _workingBrowserArgs was set inside tryChromeBridge()
        return [...this._workingBrowserArgs];
      }

      if (bridgeResult === 'locked') {
        console.warn('[FacebookSession] Browser DB locked, falling back to stored session');
        // Fall through to step 4
      }

      // 4. Use our embedded Electron session if the user logged in via the login window
      const embedded = await this.isLoggedIn();
      if (embedded) {
        try {
          const cookiesPath = await this.exportCookiesFile();
          console.log('[FacebookSession] Exported embedded session cookies:', cookiesPath);
          return ['--cookies', cookiesPath];
        } catch (exportErr: any) {
          console.error('[FacebookSession] Failed to export embedded cookies:', exportErr.message);
        }
      }
    } catch (err: any) {
      console.error('[FacebookSession] getWorkingCookieArgs error:', err.message);
    }

    // 5. Nothing worked — let yt-dlp try unauthenticated (fine for public content)
    console.log('[FacebookSession] No auth available, returning empty cookie args');
    return [];
  }
}

/* ── Singleton export ─────────────────────────────────────── */

export const facebookSessionManager = new FacebookSessionManager();
